### ISSUE TITLE
Update Event General Event (Don't include tickets)

### ISSUE THREAD

**Issue by euri16** [gdgsantodomingord/devfest-santodomingo-2023#1]
Edit the [hoverboard.config.json](https://github.com/euri16/devfest-santodomingo-2023/blob/master/data/hoverboard.config.json) file.

### Info:

- **Start Date:** Oct 6, 9:00 AM
- **End Date:** Oct 7, 6:00 PM
- **Sesiones 2022:** [Link de YouTube](https://www.youtube.com/watch?v=2ApQrCXhK7w&list=PLokIBNX1GWGsH0V2vlGCgFyqkBFSYf5C1)
- **Location:** UNPHU
- **CFP:** https://sessionize.com/devfest-santo-domingo-2023

### Tasks NOT included in this ticket:

- Pages
- Tickets

**Comment by daiivasq** [comment]
Estimación : Miércoles 19JUL 8PM

**Comment by daiivasq** [comment]
![Captura de pantalla 2023-07-17 a la(s) 7 40 37 p  m](https://github.com/gdgsantodomingord/devfest-santodomingo-2023/assets/60607967/af3fa864-f0c8-4d58-a7f6-14348ece35f0)

Se necesitaría este arte / logo con el año actualizado a 2023

**Comment by euri16** [comment]
![DF23](https://github.com/gdgsantodomingord/devfest-santodomingo-2023/assets/828824/c05bac07-74d6-4bd4-af24-25fc542802e2)

**Comment by daiivasq** [comment]
Gracias, está bien. Veré que hago para ajustarle la resolución.

**Comment by daiivasq** [comment]
Lo unico que faltaria del 'home', seria cambiar el Link de "Comprar boleta", pero como esto va de la mano con Tickets por eso no pregunte por ello. @euri16
