### ISSUE TITLE
Add link to 2022 website in the footer

### ISSUE THREAD

**Issue by euri16** [gdgsantodomingord/devfest-santodomingo-2023#13]
Add a `DevFest 2022` link to the website footer.

**Comment by daiivasq** [comment]
<img width="1728" alt="Captura de pantalla 2023-07-21 a la(s) 8 41 55 a  m" src="https://github.com/gdgsantodomingord/devfest-santodomingo-2023/assets/60607967/1be9d07f-f44a-4451-ac78-a6e4c444ca45">


Actualmente el apartado que dice "DevFest 2021", lo manda a la playlist de ese año. Yo previamente agregue un apartado de "DevFest 2022" con el playlist del 22 para que tenga el mismo curso.

¿Desea que le cambie el link a "DevFest 22" o creo un apartado nuevo que diga "DevFest 2022 website" ? @euri16

**Comment by euri16** [comment]
Vamos a dejar el texto igual pero enviarlos a la página del año pasado.

**Comment by daiivasq** [comment]
Bien
