### ISSUE TITLE
Bug: Diamond partners title not visible

### ISSUE THREAD

**Issue by euri16** [gdgsantodomingord/devfest-santodomingo-2023#22]
Check why the diamond partners group doesn't have the title:

<img width="400" alt="image" src="https://github.com/gdgsantodomingord/devfest-santodomingo-2023/assets/828824/fe01c541-82d0-48d5-83e4-65b48851305e">

Also please move Google & UNPHU to the partners section in the bottom.

**Comment by jorge150302** [comment]
There was not an element in the resources.json for this.

**Comment by euri16** [comment]
> There was not an element in the resources.json for this.

Is it possible to add it?
