### ISSUE TITLE
Reduce Top Bar Logo size

### ISSUE THREAD

**Issue by euri16** [gdgsantodomingord/devfest-santodomingo-2023#28]
If you go to one of the pages, like Team, you will see that the logo size is too big:

<img width="458" alt="image" src="https://github.com/gdgsantodomingord/devfest-santodomingo-2023/assets/828824/df61696c-2651-48b8-b6ed-1d869f94e25d">

That logo size in the HTML is 55px, we can reduce it to 35px.

**Comment by jorge150302** [comment]
It was reduced to 35px:
![image](https://github.com/gdgsantodomingord/devfest-santodomingo-2023/assets/119022384/c67140c4-9a1d-4ee6-8168-bcca9902a312)
