### ISSUE TITLE
Update Team

### ISSUE THREAD

**Issue by euri16** [gdgsantodomingord/devfest-santodomingo-2023#5]
# Team 2023

###  Eury Pérez B.
- Organizador
- Principal Android Developer
- Google Developer Expert

###  Alexander Vegas
- Co-organizador
- Senior QA Engineer
- GDG Co-organizer

### Elaine Guzmán
- Finanzas
- UX Designer
- 
### Daviana Núñez
- Sponsors & Partners
- Co-founder @ Couple Media

### Madelaine Pérez
- Speakers

### Julio Alcántara
- Core Team
- DevOps Engineer

### Miguel Vásquez
- Core Team

### Carmelo Cueto
- Core Team
- Senior Developer

Las fotos serán subidas a esta carpeta: https://drive.google.com/drive/folders/1IReUMD3GZTJRS4Xxi7AtBfHABN57Myzs?usp=sharing

**Comment by daiivasq** [comment]
![Captura de pantalla 2023-07-17 a la(s) 9 29 22 p  m](https://github.com/gdgsantodomingord/devfest-santodomingo-2023/assets/60607967/0bdd23eb-e9a9-4111-8693-d2b7edff1251)

Hola, ¿que personas hay que añadir/remover en este renglón de TEAM?

**Comment by euri16** [comment]
Actualicé la descripción del ticket con las informaciones. Las fotos serán subidas entre hoy y mañana. @daiivasq
