### ISSUE TITLE
Update Partners

### ISSUE THREAD

**Issue by euri16** [gdgsantodomingord/devfest-santodomingo-2023#9]
### Diamond

- Arroyo Consulting

### Platinum

- EvoPoint
- OrionTek
- Solvex
- Google
- UNPHU

### Gold

- Nearsure

### Silver

- Cecomsa

### Partners

- JetBrains
- Axure

**Comment by daiivasq** [comment]
Tenemos la información de los partnes que estaban este año?

**Comment by euri16** [comment]
Así es, aunque esto será una tarea recurrente porque habrá que actualizarlo a medida que vayamos recibiendo sponsors. Luego te agregaré los que tenemos hasta el momento y en que categoría cada uno.

**Comment by euri16** [comment]
@daiivasq Ya actualicé la descripción del ticket, hay varios de esos logos que ya los tenemos del año pasado, puedes ir trabajando en base a estos y más adelante te vamos enviando los demás logos. Puedes crear un PR inicial y luego creamos PRs para ir agregando.

**Comment by daiivasq** [comment]
![Captura de pantalla 2023-07-20 a la(s) 9 02 51 a  m](https://github.com/gdgsantodomingord/devfest-santodomingo-2023/assets/60607967/9e1010b8-c6e0-4bbb-9076-ab01d9c0d2ce)


Hay link para "Conviértete en Sponsor" actualizado a este año? @euri16
